
package com.sid.eau_electricite.web;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FactureEEService", targetNamespace = "http://web.eau_electricite.sid.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FactureEEService {


    /**
     * 
     * @param numContrat
     * @return
     *     returns java.util.List<com.sid.eau_electricite.web.FactureEE>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFacturesByNumContrat", targetNamespace = "http://web.eau_electricite.sid.com/", className = "com.sid.eau_electricite.web.GetFacturesByNumContrat")
    @ResponseWrapper(localName = "getFacturesByNumContratResponse", targetNamespace = "http://web.eau_electricite.sid.com/", className = "com.sid.eau_electricite.web.GetFacturesByNumContratResponse")
    @Action(input = "http://web.eau_electricite.sid.com/FactureEEService/getFacturesByNumContratRequest", output = "http://web.eau_electricite.sid.com/FactureEEService/getFacturesByNumContratResponse")
    public List<FactureEE> getFacturesByNumContrat(
        @WebParam(name = "numContrat", targetNamespace = "")
        Long numContrat);

    /**
     * 
     * @param numContrat
     * @return
     *     returns java.util.List<com.sid.eau_electricite.web.FactureEE>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFacturesImpayes", targetNamespace = "http://web.eau_electricite.sid.com/", className = "com.sid.eau_electricite.web.GetFacturesImpayes")
    @ResponseWrapper(localName = "getFacturesImpayesResponse", targetNamespace = "http://web.eau_electricite.sid.com/", className = "com.sid.eau_electricite.web.GetFacturesImpayesResponse")
    @Action(input = "http://web.eau_electricite.sid.com/FactureEEService/getFacturesImpayesRequest", output = "http://web.eau_electricite.sid.com/FactureEEService/getFacturesImpayesResponse")
    public List<FactureEE> getFacturesImpayes(
        @WebParam(name = "numContrat", targetNamespace = "")
        Long numContrat);

    /**
     * 
     * @return
     *     returns java.util.List<com.sid.eau_electricite.web.FactureEE>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFactures", targetNamespace = "http://web.eau_electricite.sid.com/", className = "com.sid.eau_electricite.web.GetFactures")
    @ResponseWrapper(localName = "getFacturesResponse", targetNamespace = "http://web.eau_electricite.sid.com/", className = "com.sid.eau_electricite.web.GetFacturesResponse")
    @Action(input = "http://web.eau_electricite.sid.com/FactureEEService/getFacturesRequest", output = "http://web.eau_electricite.sid.com/FactureEEService/getFacturesResponse")
    public List<FactureEE> getFactures();

    /**
     * 
     * @param id
     * @return
     *     returns com.sid.eau_electricite.web.FactureEE
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "payerFacture", targetNamespace = "http://web.eau_electricite.sid.com/", className = "com.sid.eau_electricite.web.PayerFacture")
    @ResponseWrapper(localName = "payerFactureResponse", targetNamespace = "http://web.eau_electricite.sid.com/", className = "com.sid.eau_electricite.web.PayerFactureResponse")
    @Action(input = "http://web.eau_electricite.sid.com/FactureEEService/payerFactureRequest", output = "http://web.eau_electricite.sid.com/FactureEEService/payerFactureResponse")
    public FactureEE payerFacture(
        @WebParam(name = "id", targetNamespace = "")
        Long id);

    /**
     * 
     * @param id
     * @return
     *     returns com.sid.eau_electricite.web.FactureEE
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFacture", targetNamespace = "http://web.eau_electricite.sid.com/", className = "com.sid.eau_electricite.web.GetFacture")
    @ResponseWrapper(localName = "getFactureResponse", targetNamespace = "http://web.eau_electricite.sid.com/", className = "com.sid.eau_electricite.web.GetFactureResponse")
    @Action(input = "http://web.eau_electricite.sid.com/FactureEEService/getFactureRequest", output = "http://web.eau_electricite.sid.com/FactureEEService/getFactureResponse")
    public FactureEE getFacture(
        @WebParam(name = "id", targetNamespace = "")
        Long id);

}
