
package com.sid.eau_electricite.web;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FactureEEService", targetNamespace = "http://web.eau_electricite.sid.com/", wsdlLocation = "http://localhost:8888/FactureEEService?wsdl")
public class FactureEEService_Service
    extends Service
{

    private final static URL FACTUREEESERVICE_WSDL_LOCATION;
    private final static WebServiceException FACTUREEESERVICE_EXCEPTION;
    private final static QName FACTUREEESERVICE_QNAME = new QName("http://web.eau_electricite.sid.com/", "FactureEEService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8888/FactureEEService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FACTUREEESERVICE_WSDL_LOCATION = url;
        FACTUREEESERVICE_EXCEPTION = e;
    }

    public FactureEEService_Service() {
        super(__getWsdlLocation(), FACTUREEESERVICE_QNAME);
    }

    public FactureEEService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), FACTUREEESERVICE_QNAME, features);
    }

    public FactureEEService_Service(URL wsdlLocation) {
        super(wsdlLocation, FACTUREEESERVICE_QNAME);
    }

    public FactureEEService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FACTUREEESERVICE_QNAME, features);
    }

    public FactureEEService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FactureEEService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FactureEEService
     */
    @WebEndpoint(name = "FactureEEServicePort")
    public FactureEEService getFactureEEServicePort() {
        return super.getPort(new QName("http://web.eau_electricite.sid.com/", "FactureEEServicePort"), FactureEEService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FactureEEService
     */
    @WebEndpoint(name = "FactureEEServicePort")
    public FactureEEService getFactureEEServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://web.eau_electricite.sid.com/", "FactureEEServicePort"), FactureEEService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FACTUREEESERVICE_EXCEPTION!= null) {
            throw FACTUREEESERVICE_EXCEPTION;
        }
        return FACTUREEESERVICE_WSDL_LOCATION;
    }

}
